/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'driverId' : [] | [Principal],
  'scheduledTime' : [] | [Time],
  'createdAt' : Time,
  'totalAmount' : bigint,
  'vendorId' : bigint,
  'customerId' : Principal,
  'landmarkNotes' : string,
}
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'orderId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : bigint,
  'stockStatus' : StockStatus,
  'name' : string,
  'description' : string,
  'vendorId' : bigint,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'food' : null } |
  { 'medicine' : null } |
  { 'grocery' : null } |
  { 'pooja' : null };
export type StockStatus = { 'inStock' : null } |
  { 'outOfStock' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : bigint,
  'status' : VendorStatus,
  'isEcoDelivery' : boolean,
  'name' : string,
  'description' : string,
  'address' : string,
  'category' : VendorCategory,
}
export type VendorCategory = { 'grocery' : null } |
  { 'pharmacy' : null } |
  { 'temple' : null } |
  { 'restaurant' : null };
export type VendorStatus = { 'closed' : null } |
  { 'open' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDriver' : ActorMethod<[bigint, Principal], undefined>,
  'createOrder' : ActorMethod<[Order, Array<OrderItem>], bigint>,
  'createProduct' : ActorMethod<[Product], bigint>,
  'createVendor' : ActorMethod<[Vendor], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getOrderItems' : ActorMethod<[bigint], Array<OrderItem>>,
  'getOrdersByCustomer' : ActorMethod<[Principal], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByVendor' : ActorMethod<[bigint], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendor' : ActorMethod<[bigint], Vendor>,
  'getVendorsByCategory' : ActorMethod<[VendorCategory], Array<Vendor>>,
  'initializeData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'updateVendor' : ActorMethod<[bigint, Vendor], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];