/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'driverId' : IDL.Opt(IDL.Principal),
  'scheduledTime' : IDL.Opt(Time),
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'vendorId' : IDL.Nat,
  'customerId' : IDL.Principal,
  'landmarkNotes' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'orderId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const StockStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'food' : IDL.Null,
  'medicine' : IDL.Null,
  'grocery' : IDL.Null,
  'pooja' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockStatus' : StockStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'vendorId' : IDL.Nat,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const VendorStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const VendorCategory = IDL.Variant({
  'grocery' : IDL.Null,
  'pharmacy' : IDL.Null,
  'temple' : IDL.Null,
  'restaurant' : IDL.Null,
});
export const Vendor = IDL.Record({
  'id' : IDL.Nat,
  'status' : VendorStatus,
  'isEcoDelivery' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'category' : VendorCategory,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDriver' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createOrder' : IDL.Func([Order, IDL.Vec(OrderItem)], [IDL.Nat], []),
  'createProduct' : IDL.Func([Product], [IDL.Nat], []),
  'createVendor' : IDL.Func([Vendor], [IDL.Nat], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrderItems' : IDL.Func([IDL.Nat], [IDL.Vec(OrderItem)], ['query']),
  'getOrdersByCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByVendor' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
  'getVendorsByCategory' : IDL.Func(
      [VendorCategory],
      [IDL.Vec(Vendor)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'updateVendor' : IDL.Func([IDL.Nat, Vendor], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'driverId' : IDL.Opt(IDL.Principal),
    'scheduledTime' : IDL.Opt(Time),
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'vendorId' : IDL.Nat,
    'customerId' : IDL.Principal,
    'landmarkNotes' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'orderId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const StockStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'food' : IDL.Null,
    'medicine' : IDL.Null,
    'grocery' : IDL.Null,
    'pooja' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockStatus' : StockStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'vendorId' : IDL.Nat,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const VendorStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const VendorCategory = IDL.Variant({
    'grocery' : IDL.Null,
    'pharmacy' : IDL.Null,
    'temple' : IDL.Null,
    'restaurant' : IDL.Null,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Nat,
    'status' : VendorStatus,
    'isEcoDelivery' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'category' : VendorCategory,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDriver' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createOrder' : IDL.Func([Order, IDL.Vec(OrderItem)], [IDL.Nat], []),
    'createProduct' : IDL.Func([Product], [IDL.Nat], []),
    'createVendor' : IDL.Func([Vendor], [IDL.Nat], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrderItems' : IDL.Func([IDL.Nat], [IDL.Vec(OrderItem)], ['query']),
    'getOrdersByCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByVendor' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
    'getVendorsByCategory' : IDL.Func(
        [VendorCategory],
        [IDL.Vec(Vendor)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'updateVendor' : IDL.Func([IDL.Nat, Vendor], [], []),
  });
};

export const init = ({ IDL }) => { return []; };