/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: bigint;
    stockStatus: StockStatus;
    name: string;
    description: string;
    vendorId: bigint;
    category: ProductCategory;
    price: bigint;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    driverId?: Principal;
    scheduledTime?: Time;
    createdAt: Time;
    totalAmount: bigint;
    vendorId: bigint;
    customerId: Principal;
    landmarkNotes: string;
}
export type Time = bigint;
export interface OrderItem {
    productId: bigint;
    productName: string;
    orderId: bigint;
    quantity: bigint;
    price: bigint;
}
export interface Vendor {
    id: bigint;
    status: VendorStatus;
    isEcoDelivery: boolean;
    name: string;
    description: string;
    address: string;
    category: VendorCategory;
}
export interface UserProfile {
    name: string;
    address: string;
    phone: string;
}
export enum OrderStatus {
    preparing = "preparing",
    cancelled = "cancelled",
    pending = "pending",
    outForDelivery = "outForDelivery",
    delivered = "delivered"
}
export enum ProductCategory {
    food = "food",
    medicine = "medicine",
    grocery = "grocery",
    pooja = "pooja"
}
export enum StockStatus {
    inStock = "inStock",
    outOfStock = "outOfStock"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VendorCategory {
    grocery = "grocery",
    pharmacy = "pharmacy",
    temple = "temple",
    restaurant = "restaurant"
}
export enum VendorStatus {
    closed = "closed",
    open = "open"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignDriver(orderId: bigint, driverId: Principal): Promise<void>;
    createOrder(order: Order, items: Array<OrderItem>): Promise<bigint>;
    createProduct(product: Product): Promise<bigint>;
    createVendor(vendor: Vendor): Promise<bigint>;
    deleteProduct(id: bigint): Promise<void>;
    deleteVendor(id: bigint): Promise<void>;
    getAllOrders(): Promise<Array<Order>>;
    getAllVendors(): Promise<Array<Vendor>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOrderById(orderId: bigint): Promise<Order>;
    getOrderItems(orderId: bigint): Promise<Array<OrderItem>>;
    getOrdersByCustomer(customerId: Principal): Promise<Array<Order>>;
    getProduct(id: bigint): Promise<Product>;
    getProductsByVendor(vendorId: bigint): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVendor(id: bigint): Promise<Vendor>;
    getVendorsByCategory(category: VendorCategory): Promise<Array<Vendor>>;
    initializeData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
    updateProduct(id: bigint, product: Product): Promise<void>;
    updateVendor(id: bigint, vendor: Vendor): Promise<void>;
}
import type { Order as _Order, OrderStatus as _OrderStatus, Product as _Product, ProductCategory as _ProductCategory, StockStatus as _StockStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Vendor as _Vendor, VendorCategory as _VendorCategory, VendorStatus as _VendorStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDriver(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDriver(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDriver(arg0, arg1);
            return result;
        }
    }
    async createOrder(arg0: Order, arg1: Array<OrderItem>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_Order_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_Order_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createProduct(arg0: Product): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_Product_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_Product_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createVendor(arg0: Vendor): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendor(to_candid_Vendor_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendor(to_candid_Vendor_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVendors();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVendors();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_Order_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_Order_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderItems(arg0: bigint): Promise<Array<OrderItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderItems(arg0);
            return result;
        }
    }
    async getOrdersByCustomer(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomer(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomer(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByVendor(arg0: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByVendor(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByVendor(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendor(arg0: bigint): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return from_candid_Vendor_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return from_candid_Vendor_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorsByCategory(arg0: VendorCategory): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorsByCategory(to_candid_VendorCategory_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorsByCategory(to_candid_VendorCategory_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_Product_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_Product_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVendor(arg0: bigint, arg1: Vendor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0, to_candid_Vendor_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0, to_candid_Vendor_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_OrderStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_StockStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockStatus): StockStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_VendorCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorCategory): VendorCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_VendorStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorStatus): VendorStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Vendor_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vendor): Vendor {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    deliveryAddress: string;
    driverId: [] | [Principal];
    scheduledTime: [] | [_Time];
    createdAt: _Time;
    totalAmount: bigint;
    vendorId: bigint;
    customerId: Principal;
    landmarkNotes: string;
}): {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    driverId?: Principal;
    scheduledTime?: Time;
    createdAt: Time;
    totalAmount: bigint;
    vendorId: bigint;
    customerId: Principal;
    landmarkNotes: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n22(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        driverId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.driverId)),
        scheduledTime: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.scheduledTime)),
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        vendorId: value.vendorId,
        customerId: value.customerId,
        landmarkNotes: value.landmarkNotes
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _VendorStatus;
    isEcoDelivery: boolean;
    name: string;
    description: string;
    address: string;
    category: _VendorCategory;
}): {
    id: bigint;
    status: VendorStatus;
    isEcoDelivery: boolean;
    name: string;
    description: string;
    address: string;
    category: VendorCategory;
} {
    return {
        id: value.id,
        status: from_candid_VendorStatus_n29(_uploadFile, _downloadFile, value.status),
        isEcoDelivery: value.isEcoDelivery,
        name: value.name,
        description: value.description,
        address: value.address,
        category: from_candid_VendorCategory_n31(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockStatus: _StockStatus;
    name: string;
    description: string;
    vendorId: bigint;
    category: _ProductCategory;
    price: bigint;
}): {
    id: bigint;
    stockStatus: StockStatus;
    name: string;
    description: string;
    vendorId: bigint;
    category: ProductCategory;
    price: bigint;
} {
    return {
        id: value.id,
        stockStatus: from_candid_StockStatus_n38(_uploadFile, _downloadFile, value.stockStatus),
        name: value.name,
        description: value.description,
        vendorId: value.vendorId,
        category: from_candid_ProductCategory_n40(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
}): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "outForDelivery" in value ? OrderStatus.outForDelivery : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): VendorStatus {
    return "closed" in value ? VendorStatus.closed : "open" in value ? VendorStatus.open : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grocery: null;
} | {
    pharmacy: null;
} | {
    temple: null;
} | {
    restaurant: null;
}): VendorCategory {
    return "grocery" in value ? VendorCategory.grocery : "pharmacy" in value ? VendorCategory.pharmacy : "temple" in value ? VendorCategory.temple : "restaurant" in value ? VendorCategory.restaurant : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: null;
} | {
    outOfStock: null;
}): StockStatus {
    return "inStock" in value ? StockStatus.inStock : "outOfStock" in value ? StockStatus.outOfStock : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    food: null;
} | {
    medicine: null;
} | {
    grocery: null;
} | {
    pooja: null;
}): ProductCategory {
    return "food" in value ? ProductCategory.food : "medicine" in value ? ProductCategory.medicine : "grocery" in value ? ProductCategory.grocery : "pooja" in value ? ProductCategory.pooja : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vendor>): Array<Vendor> {
    return value.map((x)=>from_candid_Vendor_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n36(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_StockStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): _StockStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VendorCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorCategory): _VendorCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_VendorStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorStatus): _VendorStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Vendor_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vendor): _Vendor {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: VendorStatus;
    isEcoDelivery: boolean;
    name: string;
    description: string;
    address: string;
    category: VendorCategory;
}): {
    id: bigint;
    status: _VendorStatus;
    isEcoDelivery: boolean;
    name: string;
    description: string;
    address: string;
    category: _VendorCategory;
} {
    return {
        id: value.id,
        status: to_candid_VendorStatus_n15(_uploadFile, _downloadFile, value.status),
        isEcoDelivery: value.isEcoDelivery,
        name: value.name,
        description: value.description,
        address: value.address,
        category: to_candid_VendorCategory_n17(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    driverId?: Principal;
    scheduledTime?: Time;
    createdAt: Time;
    totalAmount: bigint;
    vendorId: bigint;
    customerId: Principal;
    landmarkNotes: string;
}): {
    id: bigint;
    status: _OrderStatus;
    deliveryAddress: string;
    driverId: [] | [Principal];
    scheduledTime: [] | [_Time];
    createdAt: _Time;
    totalAmount: bigint;
    vendorId: bigint;
    customerId: Principal;
    landmarkNotes: string;
} {
    return {
        id: value.id,
        status: to_candid_OrderStatus_n5(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        driverId: value.driverId ? candid_some(value.driverId) : candid_none(),
        scheduledTime: value.scheduledTime ? candid_some(value.scheduledTime) : candid_none(),
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        vendorId: value.vendorId,
        customerId: value.customerId,
        landmarkNotes: value.landmarkNotes
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockStatus: StockStatus;
    name: string;
    description: string;
    vendorId: bigint;
    category: ProductCategory;
    price: bigint;
}): {
    id: bigint;
    stockStatus: _StockStatus;
    name: string;
    description: string;
    vendorId: bigint;
    category: _ProductCategory;
    price: bigint;
} {
    return {
        id: value.id,
        stockStatus: to_candid_StockStatus_n9(_uploadFile, _downloadFile, value.stockStatus),
        name: value.name,
        description: value.description,
        vendorId: value.vendorId,
        category: to_candid_ProductCategory_n11(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): {
    inStock: null;
} | {
    outOfStock: null;
} {
    return value == StockStatus.inStock ? {
        inStock: null
    } : value == StockStatus.outOfStock ? {
        outOfStock: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    food: null;
} | {
    medicine: null;
} | {
    grocery: null;
} | {
    pooja: null;
} {
    return value == ProductCategory.food ? {
        food: null
    } : value == ProductCategory.medicine ? {
        medicine: null
    } : value == ProductCategory.grocery ? {
        grocery: null
    } : value == ProductCategory.pooja ? {
        pooja: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorStatus): {
    closed: null;
} | {
    open: null;
} {
    return value == VendorStatus.closed ? {
        closed: null
    } : value == VendorStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VendorCategory): {
    grocery: null;
} | {
    pharmacy: null;
} | {
    temple: null;
} | {
    restaurant: null;
} {
    return value == VendorCategory.grocery ? {
        grocery: null
    } : value == VendorCategory.pharmacy ? {
        pharmacy: null
    } : value == VendorCategory.temple ? {
        temple: null
    } : value == VendorCategory.restaurant ? {
        restaurant: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    preparing: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
